### ISSUE TITLE
LOCATION_STRING isn't uploaded to the API

### ISSUE THREAD

**Issue by marrold** [jamescoxon/esp8266_gateway#2]
I've flashed the latest code and I've observed that the location isn't uploaded to the API.

The following code only adds the LOCATION_STRING if the data_count is 'a' _or_ 'z'-

```
  #ifdef LOCATION_STRING
  if(data_count=='a' or data_count=='z') {
      dataString += "L";
      dataString += LOCATION_STRING;
  }
  #endif
```

The 'a' packet isn't uploaded to the API in the 'setup' function, and the loop never reaches 'z' as it restarts after 1000 seconds, due to the default BEACON_INTERVAL being 60 seconds and 25 \* 60 = 1500.

As a work around, I've commented out the _if_ statement so the LOCATION_STRING is included in each packet-

```
  #ifdef LOCATION_STRING
  //if(data_count=='a' or data_count=='z') {
      dataString += "L";
      dataString += LOCATION_STRING;
  //}
  #endif
```

**Comment by jamescoxon** [comment]
Really good point- hadn't thought of that, I think its safe to increase the restart counter up to 5000 which should allow the gateway to loop round at least once.
Work around is obviously fine as well but probably don't need the LOCATION_STRING in every packet.
